- type: entity
  id: Bullet38_specialFMJ
  name: bullet (.38 Special FMJ)
  parent: BaseBullet
  categories: [ HideSpawnMenu ]
  components:
  - type: Projectile
    damage:
      types:
        Piercing: 20
        Structural: 20
    armorPenetration: 0.2

- type: entity
  id: Bullet38_specialRubber
  name: bullet (.38 Special rubber)
  parent: BaseBulletRubber
  categories: [ HideSpawnMenu ]
  components:
  - type: Projectile
    damage:
      types:
        Blunt: 4
