// Cata14 add; provides the F7 whitelist admin tab, allowing
// authorized (b)admins to view, add, refresh, and remove whitelist entries
using System;
using System.Linq;
using Content.Client.Administration.Systems;
using Content.Shared.Administration.Whitelist;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;

namespace Content.Client.Administration.UI.Tabs.WhitelistTab;

[GenerateTypedNameReferences]
public sealed partial class WhitelistTab : Control
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly WhitelistGuiSystem _system;

    public WhitelistTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _system = _entityManager.System<WhitelistGuiSystem>();
        _system.StateChanged += OnStateChanged;

        AddButton.OnPressed += _ => AddEntry();
        RefreshButton.OnPressed += _ => Refresh();
        UserNameOrId.OnTextEntered += _ => AddEntry();
    }

    public void Refresh()
    {
        StatusLabel.Text = "Loading whitelist...";
        _system.Refresh();
    }

    private void AddEntry()
    {
        var value = UserNameOrId.Text.Trim();
        if (string.IsNullOrWhiteSpace(value))
            return;

        StatusLabel.Text = $"Adding {value}...";
        _system.Add(value);
    }

    private void OnStateChanged(
        IReadOnlyList<WhitelistGuiEntry> entries,
        string? message,
        bool isError)
    {
        EntryList.RemoveAllChildren();

        var sortedEntries = entries
            .OrderBy(entry => entry.UserName ?? entry.UserId.ToString());

        foreach (var entry in sortedEntries)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 6,
            };

            var name = new Label
            {
                Text = entry.UserName ?? "Unknown username",
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 2,
            };

            var uid = new Label
            {
                Text = entry.UserId.ToString(),
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 3,
            };

            var remove = new Button
            {
                Text = "Remove",
            };

            var captured = entry.UserId;
            remove.OnPressed += _ => _system.Remove(captured);

            row.AddChild(name);
            row.AddChild(uid);
            row.AddChild(remove);
            EntryList.AddChild(row);
        }

        StatusLabel.Text = message ?? $"{entries.Count} whitelisted account(s).";
        StatusLabel.ModulateSelfOverride = isError ? Color.Red : null;
        UserNameOrId.Text = string.Empty;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            _system.StateChanged -= OnStateChanged;

        base.Dispose(disposing);
    }
}