using System.Linq;
using Content.Client.GameTicking.Managers;
using Content.Shared.Damage;
using Content.Shared.FixedPoint;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Content.Shared.Nutrition.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Cataclysm14.UserInterface.Systems;

[GenerateTypedNameReferences]
public sealed partial class CataclysmSidebar : UIWidget
{
    private readonly IPlayerManager _playerManager;
    private readonly IEntityManager _ent;
    private readonly IEntitySystemManager _entitySystem = default!;
    //private readonly ClientGameTicker _gameTicker;

    private readonly EntityQuery<DamageableComponent> _damageableQuery;
    private readonly EntityQuery<MobThresholdsComponent> _mobThresholdsQuery;
    private readonly EntityQuery<ThirstComponent> _thirstQuery;
    private readonly EntityQuery<HungerComponent> _hungerQuery;

    private EntityUid? _cachedPlayer = null;
    private DamageableComponent? _cachedDamageable = null;
    private MobThresholdsComponent? _cachedMobThresholds = null;
    private ThirstComponent? _cachedThirst = null;
    private HungerComponent? _cachedHunger = null;

    private TimeSpan _cachedTime = TimeSpan.Zero;

    private FixedPoint2 _deadThreshold = FixedPoint2.New(200);

    public CataclysmSidebar()
    {
        RobustXamlLoader.Load(this);
        _playerManager = IoCManager.Resolve<IPlayerManager>();
        _ent = IoCManager.Resolve<IEntityManager>();
        //_gameTiming = IoCManager.Resolve<GameTiming>(); crash bruh because too early
        _entitySystem = IoCManager.Resolve<IEntitySystemManager>();

        //_gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>(); crash bruh because too early

        _damageableQuery = _ent.GetEntityQuery<DamageableComponent>();
        _mobThresholdsQuery = _ent.GetEntityQuery<MobThresholdsComponent>();
        _thirstQuery = _ent.GetEntityQuery<ThirstComponent>();
        _hungerQuery = _ent.GetEntityQuery<HungerComponent>();
    }

    protected override void FrameUpdate(FrameEventArgs args) // sorry, mr. FPS
    {
        var u = _playerManager.LocalEntity;
        if (u == null)
        {
            HealthContainer.Visible = false;
            return;
        }

        HealthContainer.Visible = true;

        //var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan); // from PdaMenu
        /*var stationTime = _gameTicker.RoundDuration();
        if (stationTime != _cachedTime)
        {
            _cachedTime = stationTime;
            TimeLabel.Text = stationTime.ToString("hh\\:mm\\:ss");
        } */

        if (u != _cachedPlayer)
        {
            _cachedPlayer = u;
            _damageableQuery.TryComp(u, out _cachedDamageable);
            _mobThresholdsQuery.TryComp(u, out _cachedMobThresholds);
            _thirstQuery.TryComp(u, out _cachedThirst);
            _hungerQuery.TryComp(u, out _cachedHunger);

            var dead = _cachedMobThresholds?.Thresholds.FirstOrDefault(t => t.Value == MobState.Dead).Key;
            if (dead is {} deady) // fck c# why i cant just == null
                _deadThreshold = deady;
        }

        if (_cachedDamageable == null || _cachedMobThresholds == null)
            HealthContainer.Visible = false;
        else
        {
            HealthContainer.Visible = true;

            // 1.0f -> 100, so 9% = 9, 18% = 18, etc.
            var (healthValue, healthColor) = (_cachedDamageable.Damage.GetTotal() / _deadThreshold).Value switch
            {
               < 9 => ("|||||", new Color(0, 110, 0)),
               < 18 => ("||||\\", new Color(0, 110, 0)),
               < 27 => ("||||.", new Color(0, 110, 0)), // dark green, thx paint
               < 36 => ("|||\\.", Color.Green),
               < 45 => ("|||..", Color.Green),
               < 54 => ("||\\..", Color.Yellow),
               < 63 => ("||...", Color.Yellow),
               < 72 => ("|\\...", new Color(255, 150, 150)),
               < 81 => ("|....", new Color(255, 150, 150)), // pink
               < 90 => ("\\....", Color.Red),
               >= 90 => (".....", Color.Red),
            };

            HealthLabel.Text = healthValue;
            HealthLabel.Modulate = healthColor;
        }

        if (_cachedThirst == null)
            ThirstContainer.Visible = false;
        else
        {
            ThirstContainer.Visible = true;

            var (value, color) = _cachedThirst.CurrentThirstThreshold switch
            {
                ThirstThreshold.Dead => ("Dead", Color.Red),
                ThirstThreshold.Parched => ("Parched", Color.Red),
                ThirstThreshold.Thirsty => ("Thirsty", Color.Yellow),
                ThirstThreshold.Okay => ("Okay", Color.Green),
                ThirstThreshold.OverHydrated => ("Over hydrated", new Color(0, 110, 0)), // dark green
                _ => ("Unknown", Color.Gray)
            };

            ThirstLabel.Text = value;
            ThirstLabel.Modulate = color;
        }

        if (_cachedHunger == null)
            HungerContainer.Visible = false;
        else
        {
            HungerContainer.Visible = true;

            var (value, color) = _cachedHunger.CurrentThreshold switch
            {
                HungerThreshold.Dead => ("Dead", Color.Red),
                HungerThreshold.Starving => ("Starving", Color.Red),
                HungerThreshold.Peckish => ("Peckish", Color.Yellow),
                HungerThreshold.Okay => ("Okay", Color.Green),
                HungerThreshold.Overfed => ("Overfed", new Color(0, 110, 0)), // dark green
                _ => ("Unknown", Color.Gray)
            };

            HungerLabel.Text = value;
            HungerLabel.Modulate = color;
        }

        base.FrameUpdate(args);
    }
}

