# Base mob components that originate from ES.
- type: entity
  id: ESBaseMob
  abstract: true
  components:
  - type: ESViewcone
    grainBase: 0.1
    grainMultiplier: 0.15
  - type: ESViewconeOccludable
  - type: ESHoldToFace
