- type: entity
  id: BaseSpeedLoader38_special
  name: "speed loader (.38 Special FMJ)"
  parent: BaseItem
  abstract: true
  components:
  - type: Tag
    tags:
      - SpeedLoader38_specialFMJ
  - type: SpeedLoader
  - type: BallisticAmmoProvider
    whitelist:
      tags:
        - Cartridge38_specialFMJ
    capacity: 8
  - type: Sprite
  - type: ContainerContainer
    containers:
      ballistic-ammo: !type:Container
        ents: []

- type: entity
  id: SpeedLoader38_specialFMJ
  name: "speed loader (.38 Special FMJ)"
  parent: BaseSpeedLoader38_special
  components:
  - type: BallisticAmmoProvider
    proto: Cartridge38_specialFMJ
  - type: Icon
    sprite: _Cataclysm14/Objects/Weapons/SpeedLoaders/38_special/38_special.rsi
    state: icon
  - type: Sprite
    sprite: _Cataclysm14/Objects/Weapons/SpeedLoaders/38_special/38_special.rsi
    layers:
      - state: base
        map: [ "enum.GunVisualLayers.Base" ]
      - state: base-8
        map: [ "enum.GunVisualLayers.Mag" ]
  - type: MagazineVisuals
    magState: base
    steps: 9
    zeroVisible: false
  - type: Appearance

- type: entity
  id: SpeedLoader38_specialEmpty
  name: "speed loader (.38 Special any)"
  parent: SpeedLoader38_specialFMJ
  components:
  - type: BallisticAmmoProvider
    proto: null
  - type: Icon
    sprite: _Cataclysm14/Objects/Weapons/SpeedLoaders/38_special/38_special.rsi
    state: base
  - type: Sprite
    sprite: _Cataclysm14/Objects/Weapons/SpeedLoaders/38_special/38_special.rsi
    layers:
      - state: base
        map: [ "enum.GunVisualLayers.Base" ]
      - state: base-8
        map: [ "enum.GunVisualLayers.Mag" ]

- type: entity
  id: SpeedLoader38_specialRubber
  name: "speed loader (.38 Special rubber)"
  parent: BaseSpeedLoader38_special
  components:
  - type: BallisticAmmoProvider
    proto: Cartridge38_specialRubber
  - type: Icon
    sprite: _Cataclysm14/Objects/Weapons/SpeedLoaders/38_special/38_special.rsi
    state: rubber-icon
  - type: Sprite
    sprite: _Cataclysm14/Objects/Weapons/SpeedLoaders/38_special/38_special.rsi
    layers:
      - state: base
        map: [ "enum.GunVisualLayers.Base" ]
      - state: rubber-8
        map: [ "enum.GunVisualLayers.Mag" ]
  - type: MagazineVisuals
    magState: rubber
    steps: 9
    zeroVisible: false
  - type: Appearance
