using System.Linq;
using Content.Client._Cataclysm14.UserInterface.Controls;
using Content.Shared._Cataclysm14.Crafting;
using Content.Shared._Cataclysm14.Crafting.Conditions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Cataclysm14.Crafting;

[GenerateTypedNameReferences]
public sealed partial class CraftingWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _proto = null!;

    //private FrozenDictionary<ProtoId<CraftingCategoryPrototype>, >
    private readonly Dictionary<CraftingCategoryPrototype, List<CraftingSubCategoryPrototype>> _categories = new(16);
    private readonly Dictionary<CraftingSubCategoryPrototype, List<ItemList.Item>> _recipesByCategory = new(16);

    private CraftingCategoryPrototype _currentCategory = default!;
    private CraftingSubCategoryPrototype _currentSubCategory = default!;
    private CraftingRecipePrototype _currentRecipe = default!;

    public CraftingWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.Instance?.InjectDependencies(this);

        var catById = new Dictionary<string, CraftingCategoryPrototype>(16);
        var subCatById = new Dictionary<string, CraftingSubCategoryPrototype>(16);

        foreach (var craftingCategoryPrototype in _proto.EnumeratePrototypes<CraftingCategoryPrototype>())
        {
            var proto = craftingCategoryPrototype;
            var butt = new CataButton()
            {
                Text = proto.ID,
            };
            butt.OnPressed += (_) => ChangeCategory(proto);
            CategoryContainer.AddChild(butt);
            _categories.Add(proto, new(6));
            catById[proto.ID] = proto;
        }

        foreach (var craftingSubCategoryPrototype in _proto.EnumeratePrototypes<CraftingSubCategoryPrototype>())
        {
            var papa = catById[craftingSubCategoryPrototype.Parent];
            _categories[papa].Add(craftingSubCategoryPrototype);
            _recipesByCategory.Add(craftingSubCategoryPrototype, new(32));
            subCatById.Add(craftingSubCategoryPrototype.ID, craftingSubCategoryPrototype);
        }

        foreach (var craftingRecipe in _proto.EnumeratePrototypes<CraftingRecipePrototype>())
        {
            var cat = subCatById[craftingRecipe.SubCategory];
            _recipesByCategory[cat].Add(new (RecipeList)
            {
                Text = craftingRecipe.Name,
                Metadata = craftingRecipe,
            });
        }

        RecipeList.OnItemSelected += OnRecipeSelected;

        if (_categories.Count != 0)
            ChangeCategory(_categories.First().Key);
    }

    private void OnRecipeSelected(ItemList.ItemListSelectedEventArgs obj)
    {
        _currentRecipe = (CraftingRecipePrototype)RecipeList[obj.ItemIndex].Metadata!;
        RequirementsContainer.Children.Clear();
        foreach (var currentRecipeCondition in _currentRecipe.Conditions)
        {
            FillRequirements(currentRecipeCondition);
        }

        if (_proto.Resolve(_currentRecipe.Item, out var item))
        {
            RecipeResultLabel.Text = Loc.GetString(item.Name);
        }
        else
        {
            RecipeResultLabel.Text = "error";
        }
    }

    private void FillRequirements(CraftingCondition condition)
    {
        switch (condition)
        {
            case ItemCondition itemCondition:
            {
                if (!_proto.Resolve(itemCondition.Item, out var item))
                {
                    RequirementsContainer.AddChild(new RichTextLabel()
                    {
                        Text = $"> [color=red]error[/color]"
                    });
                    break;
                }

                RequirementsContainer.AddChild(new RichTextLabel()
                {
                    Text = $"> [color=red]{itemCondition.Amount} {Loc.GetString(item.Name)}[/color]"
                });
                break;
            }
            case OneOfCondition oneOf:
                break;
            case ToolCondition toolCondition:
            {
                if (!_proto.Resolve(toolCondition.Tool, out var tool))
                {
                    RequirementsContainer.AddChild(new RichTextLabel()
                    {
                        Text = $"> [color=red]error[/color]"
                    });
                    break;
                }

                var loc = Loc.GetString(tool.Name);
                RequirementsContainer.AddChild(new RichTextLabel()
                {
                    Text = $"> [color=red]1 tool with {loc} or more[/color]"
                });
                break;
            }
        }
    }

    private void ChangeCategory(CraftingCategoryPrototype category)
    {
        if (_currentCategory == category)
            return;
        _currentCategory = category;
        SubCategoryContainer.RemoveAllChildren();
        var subCats = _categories[category];
        var first = true;
        foreach (var subCat in subCats)
        {
            var subCatCopy = subCat;
            var butt = new CataButton()
            {
                Text = subCat.ID,
            };
            butt.OnPressed += _ => ChangeSubCategory(subCatCopy);
            SubCategoryContainer.AddChild(butt);
            if (first) // shitcode
            {
                first = false;
            }
        }
    }

    private void ChangeSubCategory(CraftingSubCategoryPrototype subCategory)
    {
        if (_currentSubCategory == subCategory)
            return;
        _currentSubCategory = subCategory;
        RecipeList.Clear();
        RecipeList.SetItems(_recipesByCategory[subCategory]);
        RecipeList[0].Selected = true;
    }
}

