using Content.Client.UserInterface.Controls;
using Content.Shared._Cataclysm14.MapGen;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Cataclysm14.MapGen._Debug;

[GenerateTypedNameReferences]
public sealed partial class ViewMapWindow : DefaultWindow
{
    private readonly IEntityManager _ent;
    private readonly IPrototypeManager _proto;
    private readonly IComponentFactory _componentFactory;

    public ViewMapWindow()
    {
        RobustXamlLoader.Load(this);

        _ent = IoCManager.Resolve<IEntityManager>();
        _proto = IoCManager.Resolve<IPrototypeManager>();
        _componentFactory = IoCManager.Resolve<IComponentFactory>();

        var playerEnt = IoCManager.Resolve<IPlayerManager>().LocalEntity;

        if (!_ent.TryGetComponent(playerEnt, out TransformComponent? xform))
        {
            AddChild(new Label()
            {
                Text = "Error: where are you???",
            });
            return;
        }

        if (!_ent.TryGetComponent(xform.MapUid, out MapGenComponent? mapGen))
        {
            AddChild(new Label()
            {
                Text = "Error: cant get chunks for this map",
            });
            return;
        }

        PopMap(mapGen);
    }

    private void PopMap(MapGenComponent map)
    {
        var baseContainer = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 1,
            HorizontalExpand = true,
            VerticalExpand = true,
            HorizontalAlignment = HAlignment.Left,
            VerticalAlignment = VAlignment.Top,
            MinSize = new(400, 400),
        };
        ScrollCon.AddChild(baseContainer);
        for (var x = map.MapSize.Left; x <= map.MapSize.Right; x++)
        {
            var row = new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 1,
                HorizontalExpand = true,
                VerticalExpand = true,
                HorizontalAlignment = HAlignment.Left,
                VerticalAlignment = VAlignment.Top,
            };
            baseContainer.AddChild(row);
            for (var y = map.MapSize.Bottom; y <= map.MapSize.Top; y++)
            {
                var column = new BoxContainer()
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    SeparationOverride = 0,
                    HorizontalExpand = true,
                    VerticalExpand = true,
                    HorizontalAlignment = HAlignment.Left,
                    VerticalAlignment = VAlignment.Top,
                };
                row.AddChild(column);
                PopChunk(column, map.Chunks[new(x,y)]);
            }
        }
    }

    private void PopChunk(Container grid, EntProtoId<MapGenChunkComponent>[][] chunkData)
    {
        for (var x = 0; x < MapGenComponent.ChunkSize; x++)
        {
            var row = new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 0,
                HorizontalExpand = true,
                VerticalExpand = true,
                HorizontalAlignment = HAlignment.Left,
                VerticalAlignment = VAlignment.Top,
            };
            grid.AddChild(row);
            for (var y = 0; y < MapGenComponent.ChunkSize; y++)
            {
                if (!string.IsNullOrEmpty(chunkData[x][y].Id) && chunkData[x][y].TryGet(out var chunk, _proto, _componentFactory))
                {
                    row.AddChild(new Label()
                    {
                        Text = chunk.Char,
                        FontColorOverride = chunk.CharColor,
                        //HorizontalExpand = true,
                        //VerticalExpand = true,
                        SetSize = new(13,13),
                    });
                }
                else
                {
                    row.AddChild(new Label()
                    {
                        Text = "E",
                        FontColorOverride = Color.DarkRed,
                        //HorizontalExpand = true,
                        //VerticalExpand = true,
                        SetSize = new(13,13),
                    });
                }
            }
        }
    }
}

